#!/usr/bin/env python
"""
Flask API to serve 3D GLB models from the models/ directory.

Endpoints:
  GET  /                          → API info + list of all products
  GET  /models                    → JSON list of all models with live links
  GET  /models/<id>               → single product info + link by ID
  GET  /models/<id>/<folder>/<file> → serve the actual GLB file
  GET  /viewer/<id>               → embedded 3D viewer for a product

Every GLB in models/ is auto-discovered from manifest.json
(generated by batch_process.py).

Run:
  python api.py                  → http://0.0.0.0:5050
  python api.py --port 8080      → http://0.0.0.0:8080
"""

import os
import sys
import json
import argparse
import re
from pathlib import Path
from urllib.parse import unquote

try:
    from flask import Flask, jsonify, send_from_directory, request, abort, render_template_string
except ImportError:
    sys.exit("ERROR: pip install --user flask")

try:
    from anthropic import Anthropic
except ImportError:
    print("WARNING: anthropic not installed. AI endpoints will use fallback.")
    Anthropic = None

# Load .env file — try dotenv first, then manual parse as fallback
def _load_env_file():
    """Load .env file into os.environ, trying multiple approaches."""
    env_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), ".env")
    # Approach 1: python-dotenv
    try:
        from dotenv import load_dotenv
        load_dotenv(env_path)
        return
    except PermissionError:
        pass
    except ImportError:
        pass
    except Exception:
        pass
    # Approach 2: manual parse (handles permission issues with dotenv internals)
    try:
        with open(env_path, 'r') as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith('#') or '=' not in line:
                    continue
                key, _, value = line.partition('=')
                key = key.strip()
                value = value.strip().strip('"').strip("'")
                if key and not os.environ.get(key):
                    os.environ[key] = value
    except Exception:
        pass

_load_env_file()


# ── Config ───────────────────────────────────────────────────────────────
MODELS_DIR    = os.path.join(os.path.dirname(os.path.abspath(__file__)), "models")
MANIFEST_FILE = os.path.join(MODELS_DIR, "manifest.json")

# Kiro API Configuration
# Try multiple environment variable names for flexibility
KIRO_API_KEY = os.getenv('KIRO_API_KEY') or os.getenv('kiro_key') or os.getenv('KIRO_KEY')
KIRO_BASE_URL = 'https://api.kiro.cheap'
KIRO_MODEL = 'claude-sonnet-4-20250514'  # Default model

app = Flask(__name__)

# Initialize Kiro client if API key is available
kiro_client = None
if Anthropic and KIRO_API_KEY:
    try:
        kiro_client = Anthropic(
            api_key=KIRO_API_KEY,
            base_url=KIRO_BASE_URL,
        )
        print(f"✅ Kiro AI client initialized (model: {KIRO_MODEL})")
    except Exception as e:
        print(f"⚠️  Failed to initialize Kiro client: {e}")
        kiro_client = None
else:
    if not KIRO_API_KEY:
        print("⚠️  KIRO_API_KEY not set. AI endpoints will use fallback pattern matching.")
    if not Anthropic:
        print("⚠️  Anthropic SDK not installed. AI endpoints will use fallback pattern matching.")


# ── Excel data loader ─────────────────────────────────────────────────────

EXCEL_DATA = {}  # id → {price, category, tags, short_desc, description, sku, type, ...}

def load_excel_data():
    """Load real product data from products.xlsx using zipfile+xml (lightweight).
    Populates the global EXCEL_DATA dict keyed by product ID."""
    global EXCEL_DATA
    xlsx_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "products.xlsx")
    if not os.path.exists(xlsx_path):
        print("⚠️  products.xlsx not found. Product data will use inferred values.")
        return

    try:
        import zipfile
        import xml.etree.ElementTree as ET

        z = zipfile.ZipFile(xlsx_path)
        # Read shared strings
        ns = {'s': 'http://schemas.openxmlformats.org/spreadsheetml/2006/main'}
        tree = ET.parse(z.open('xl/sharedStrings.xml'))
        strings = []
        for si in tree.findall('.//s:si', ns):
            text_parts = []
            for t in si.findall('.//s:t', ns):
                if t.text:
                    text_parts.append(t.text)
            strings.append(''.join(text_parts))

        # Read sheet data
        tree2 = ET.parse(z.open('xl/worksheets/sheet1.xml'))
        rows = tree2.findall('.//s:sheetData/s:row', ns)

        # Column mapping: A=ID, B=Image, C=SKU, D=Name, E=Type, F=Status,
        # G=Regular Price, H=Sale Price, I=Stock Status, J=Stock Quantity,
        # K=Categories, L=Tags, M=Short Description, N=Description

        for row in rows[1:]:  # skip header
            cells = {}
            for cell in row:
                ref = cell.get('r')
                col = ''.join(c for c in ref if c.isalpha())
                cell_type = cell.get('t')
                val_elem = cell.find('s:v', ns)
                if val_elem is not None:
                    val = val_elem.text
                    if cell_type == 's':
                        idx = int(val)
                        val = strings[idx] if idx < len(strings) else val
                    cells[col] = val

            pid = cells.get('A')
            if not pid:
                continue

            # Clean up HTML entities
            def clean_html(text):
                if not text:
                    return text
                return (text.replace('&amp;', '&')
                            .replace('&lt;', '<')
                            .replace('&gt;', '>')
                            .replace('&quot;', '"')
                            .replace('&#39;', "'"))

            EXCEL_DATA[str(pid)] = {
                'sku': cells.get('C', ''),
                'name': cells.get('D', ''),
                'type': cells.get('E', ''),
                'status': cells.get('F', ''),
                'regular_price': cells.get('G', ''),
                'sale_price': cells.get('H', ''),
                'stock_status': cells.get('I', ''),
                'stock_quantity': cells.get('J', ''),
                'categories': clean_html(cells.get('K', '')),
                'tags': clean_html(cells.get('L', '')),
                'short_description': clean_html(cells.get('M', '')),
                'description': clean_html(cells.get('N', '')),
            }

        z.close()
        print(f"✅ Loaded {len(EXCEL_DATA)} products from products.xlsx")
    except Exception as e:
        print(f"⚠️  Error reading products.xlsx: {e}")
        import traceback
        traceback.print_exc()


# Load Excel data at import time
load_excel_data()


# ── Helpers ──────────────────────────────────────────────────────────────

def load_manifest():
    """Load manifest.json; fall back to scanning folders if not found."""
    if os.path.exists(MANIFEST_FILE):
        with open(MANIFEST_FILE) as f:
            return json.load(f)

    # Fallback: scan models/ for any model.glb
    manifest = []
    if not os.path.isdir(MODELS_DIR):
        return manifest
    for folder in sorted(os.listdir(MODELS_DIR)):
        folder_path = os.path.join(MODELS_DIR, folder)
        if not os.path.isdir(folder_path):
            continue
        # Find GLB files
        glbs = [f for f in os.listdir(folder_path) if f.lower().endswith('.glb')]
        if not glbs:
            continue
        # Try to parse ID from folder name  (format: {id}_{name})
        parts = folder.split('_', 1)
        pid = parts[0] if parts[0].isdigit() else folder
        name = parts[1].replace('_', ' ') if len(parts) > 1 else folder
        for glb in glbs:
            manifest.append({
                "id":     pid,
                "name":   name,
                "folder": folder,
                "glb":    glb,
                "status": "ok",
            })
    return manifest


def get_base_url():
    """Return the base URL for building live links.
    Respects X-Forwarded-Proto/Host from reverse proxies (nginx, Cloudflare)."""
    proto = request.headers.get('X-Forwarded-Proto', request.scheme)
    host = request.headers.get('X-Forwarded-Host', request.host)
    return f"{proto}://{host}"


def call_kiro(prompt, system_prompt=None, max_tokens=4096, retries=2):
    """Call Kiro API and extract text response (handling thinking blocks).
    Retries on transient errors."""
    if not kiro_client:
        print("[Kiro] Client not initialized — skipping LLM call")
        return None
    
    import time
    last_error = None
    for attempt in range(1 + retries):
        try:
            messages = [{"role": "user", "content": prompt}]
            
            kwargs = {
                "model": KIRO_MODEL,
                "max_tokens": max_tokens,
                "messages": messages,
            }
            # Anthropic SDK uses 'system' parameter, not a system message
            if system_prompt:
                kwargs["system"] = system_prompt
            
            response = kiro_client.messages.create(**kwargs)
            
            # Extract text from response (handle thinking blocks)
            text_content = ""
            block_types = []
            for content_block in response.content:
                block_types.append(content_block.type)
                if content_block.type == "text":
                    text_content += content_block.text
                # Skip thinking blocks - they're internal reasoning
            
            if not text_content.strip():
                print(f"[Kiro] Warning: empty text response. Block types: {block_types}, stop_reason: {getattr(response, 'stop_reason', '?')}")
                # Retry if we got an empty response
                if attempt < retries:
                    time.sleep(0.5)
                    continue
            
            return text_content.strip() if text_content.strip() else None
        except Exception as e:
            last_error = e
            if attempt < retries:
                wait = 0.5 * (attempt + 1)
                print(f"[Kiro] Attempt {attempt+1} failed ({type(e).__name__}), retrying in {wait}s...")
                time.sleep(wait)
                continue
            print(f"[Kiro] All {retries+1} attempts failed. Last error: {type(e).__name__}: {e}")
            return None


def parse_ai_response(text, default_actions=None, default_suggestions=None):
    """Parse AI response text to extract actions and suggestions."""
    if not text:
        return {
            "message": "I apologize, but I couldn't process that request.",
            "actions": default_actions or [],
            "suggestions": default_suggestions or [],
        }
    
    actions = default_actions or []
    suggestions = default_suggestions or []
    
    # Try to extract JSON actions from response (if AI includes structured data)
    import json
    json_match = re.search(r'\{[^{}]*"type"[^{}]*\}', text, re.IGNORECASE)
    if json_match:
        try:
            parsed = json.loads(json_match.group(0))
            if isinstance(parsed, dict) and "actions" in parsed:
                actions.extend(parsed["actions"])
            if isinstance(parsed, dict) and "suggestions" in parsed:
                suggestions.extend(parsed["suggestions"])
        except:
            pass
    
    # Extract action intents from text
    text_lower = text.lower()
    
    # Navigation intents
    if 'navigate' in text_lower or 'go to' in text_lower or '/store' in text:
        if '/store' in text or 'store' in text_lower:
            actions.append({"type": "NAVIGATE", "payload": {"path": "/store"}})
    
    # Product opening intents
    product_id_match = re.search(r'product[_\s]*(?:id[_\s]*)?(\d+)', text, re.IGNORECASE)
    if product_id_match:
        actions.append({"type": "OPEN_PRODUCT", "payload": {"productId": product_id_match.group(1)}})
    
    # Filter intents
    if 'microsoft' in text_lower:
        actions.append({"type": "APPLY_FILTERS", "payload": {"brand": ["Microsoft"]}})
    elif 'adobe' in text_lower:
        actions.append({"type": "APPLY_FILTERS", "payload": {"brand": ["Adobe"]}})
    elif 'autodesk' in text_lower or 'autocad' in text_lower:
        actions.append({"type": "APPLY_FILTERS", "payload": {"brand": ["Autodesk"]}})
    
    # Search intents
    search_match = re.search(r'search[_\s]+for[_\s]+["\']?([^"\']+)["\']?', text, re.IGNORECASE)
    if search_match:
        actions.append({"type": "SET_SEARCH", "payload": {"query": search_match.group(1).strip()}})
    
    return {
        "message": text,
        "actions": actions,
        "suggestions": suggestions[:5],
    }


def enrich_product(m, base_url):
    """Enrich product data using real Excel data when available, with inferred fallbacks."""
    name = m.get('name', '')
    folder = m.get('folder', '')
    pid = str(m.get('id', ''))

    # Try to get real data from Excel
    excel = EXCEL_DATA.get(pid, {})

    # ── Categories: use Excel 'categories' (may be comma-separated) ──
    raw_categories = excel.get('categories', '').strip()
    if raw_categories:
        categories_list = [c.strip() for c in raw_categories.split(',') if c.strip()]
    else:
        # Fallback: infer from name
        categories_list = ['Software']
        if any(x in name.lower() for x in ['office', 'word', 'excel', 'powerpoint', 'outlook']):
            categories_list = ['Microsoft Office']
        elif any(x in name.lower() for x in ['autocad', 'revit', 'maya', '3ds max', 'civil 3d']):
            categories_list = ['Architecture and Engineer']
        elif any(x in name.lower() for x in ['adobe', 'photoshop', 'illustrator', 'premiere', 'creative cloud']):
            categories_list = ['Adobe']
        elif any(x in name.lower() for x in ['windows', 'server', 'sql']):
            categories_list = ['Windows']
        elif any(x in name.lower() for x in ['kaspersky', 'security', 'antivirus']):
            categories_list = ['Security']
    # Primary category is the first one
    category = categories_list[0] if categories_list else 'Software'

    # ── Brand: infer from ALL categories and name ──
    brand = 'Other'
    name_lower = name.lower()
    # Use individual category names (lowercased) for precise matching
    cats_lower_list = [c.lower() for c in categories_list]
    # Combined text only for substring checks where appropriate
    all_cats_lower = ' '.join(cats_lower_list)
    
    # Helper: check if ANY individual category starts with a prefix
    def any_cat_starts(prefix):
        return any(c.startswith(prefix) for c in cats_lower_list)
    # Helper: check if ANY individual category equals a value
    def any_cat_equals(val):
        return val in cats_lower_list
    
    # Autodesk-related category keywords (checked as substrings in cat names)
    autodesk_cat_keywords = ['autodesk', 'autocad', '3ds max', 'civil 3d', 'fusion 360',
                             'inventor', 'maya', 'naviswork', 'revit', 'aec collection',
                             'architecture and engineer', 'dmc', 'mec collection', 'infodrainage']
    
    # Check Adobe FIRST (before Microsoft) since "Office Applications" is a generic category
    if 'adobe' in name_lower or any_cat_equals('adobe'):
        brand = 'Adobe'
    elif any(kw in name_lower or kw in all_cats_lower for kw in autodesk_cat_keywords):
        brand = 'Autodesk'
    elif ('microsoft' in name_lower or any_cat_starts('microsoft') or
          any_cat_starts('windows') or any_cat_starts('sql server') or
          any_cat_equals('dynamics 365') or any_cat_starts('microsoft power bi') or
          any_cat_starts('microsoft visual studio') or any_cat_starts('microsoft visio') or
          any_cat_starts('microsoft project') or any_cat_starts('share point') or
          any_cat_starts('exchange server') or any_cat_starts('office 2') or
          any_cat_starts('microsoft office')):
        brand = 'Microsoft'
    elif 'chaos' in name_lower or 'v-ray' in name_lower or 'enscape' in name_lower or 'corona' in name_lower:
        brand = 'Chaos'
    elif 'sketchup' in name_lower or any_cat_starts('sketchup'):
        brand = 'SketchUp'
    elif 'kaspersky' in name_lower:
        brand = 'Kaspersky'
    elif 'rhino' in name_lower:
        brand = 'Rhino'

    # ── License type: infer from product type or name ──
    license_type = 'Subscription'
    product_type = excel.get('type', '').lower()
    if 'lifetime' in name.lower() or 'perpetual' in name.lower():
        license_type = 'Lifetime'
    elif 'mak' in name.lower():
        license_type = 'MAK'
    elif 'cal' in name.lower() or 'device cal' in name.lower():
        license_type = 'Device CAL'
    elif product_type == 'variable':
        license_type = 'Variable'
    elif product_type == 'variation':
        license_type = 'Subscription'

    # ── Price: use real Excel price ──
    price = None
    regular_price = excel.get('regular_price', '')
    sale_price = excel.get('sale_price', '')
    if sale_price and sale_price.strip():
        try:
            price = f"AED {float(sale_price):,.2f}"
        except (ValueError, TypeError):
            pass
    if not price and regular_price and regular_price.strip():
        try:
            price = f"AED {float(regular_price):,.2f}"
        except (ValueError, TypeError):
            pass
    if not price:
        price = "Contact for pricing"

    # ── Description: use real short_description or full description ──
    short_desc = excel.get('short_description', '').strip()
    full_desc = excel.get('description', '').strip()
    # Strip HTML tags from descriptions
    import re as _re
    if short_desc:
        short_desc = _re.sub(r'<[^>]+>', '', short_desc).strip()
    if full_desc:
        full_desc = _re.sub(r'<[^>]+>', '', full_desc).strip()
    description = short_desc or full_desc or f"Official {brand} license. {category} software solution."

    # ── Tags: use real tags + categories + brand ──
    real_tags = [t.strip() for t in excel.get('tags', '').split(',') if t.strip()] if excel.get('tags') else []
    tags = list(set(categories_list + [brand, license_type] + real_tags))

    # ── SKU ──
    sku = excel.get('sku', '')

    # ── Stock ──
    stock_status = excel.get('stock_status', 'instock')

    return {
        "id": m.get('id'),
        "name": name,
        "folder": folder,
        "filename": m.get('glb'),
        "link": f"{base_url}/models/{m['id']}/{folder}/{m.get('glb')}",
        "viewer": f"{base_url}/viewer/{m['id']}",
        "category": category,
        "categories": categories_list,
        "brand": brand,
        "licenseType": license_type,
        "price": price,
        "description": description,
        "fullDescription": full_desc or description,
        "tags": tags,
        "sku": sku,
        "stockStatus": stock_status,
        "status": m.get('status', 'ok'),
    }


# ── Search helpers ────────────────────────────────────────────────────────

def score_product(product, query):
    """Score a product against a search query using token-based matching.
    Split query into words and check each word against product fields.
    Returns a score (0 = no match)."""
    if not query:
        return 0

    query_lower = query.lower().strip()
    if not query_lower:
        return 0

    # Searchable text from product
    name_lower = product.get('name', '').lower()
    brand_lower = product.get('brand', '').lower()
    # Support multi-category products
    categories = product.get('categories', [product.get('category', '')])
    category_lower = ' '.join(c.lower() for c in categories)
    desc_lower = product.get('description', '').lower()
    tags_lower = ' '.join(t.lower() for t in product.get('tags', []))
    folder_lower = product.get('folder', '').lower()
    all_text = f"{name_lower} {brand_lower} {category_lower} {desc_lower} {tags_lower} {folder_lower}"

    # First try: exact full query match in name (highest score)
    if query_lower in name_lower:
        return 100
    
    # Second: exact full query match in category or tags
    if query_lower in category_lower:
        return 80
    if query_lower in tags_lower:
        return 60

    # Token-based matching — strip punctuation from tokens
    tokens = [re.sub(r'[?!.,;:\'\"]+', '', t) for t in query_lower.split()]
    tokens = [t for t in tokens if len(t) > 1]  # skip single chars / empty
    if not tokens:
        return 0

    matched = 0
    name_matched = 0
    score = 0
    for token in tokens:
        if token in name_lower:
            score += 10
            matched += 1
            name_matched += 1
        elif token in brand_lower:
            score += 5
            matched += 1
        elif token in category_lower:
            score += 4
            matched += 1
        elif token in tags_lower:
            score += 3
            matched += 1
        elif token in folder_lower:
            score += 2
            matched += 1
        elif token in desc_lower:
            score += 1
            matched += 1

    # Big bonus if ALL tokens matched in name specifically
    if name_matched == len(tokens) and name_matched > 1:
        score += 30
    # Bonus if ALL tokens matched anywhere
    elif matched == len(tokens) and matched > 0:
        score += 15
    # Penalty if less than half matched
    elif matched > 0 and matched < len(tokens) / 2:
        score = score // 2
    # No match at all
    elif matched == 0:
        return 0
    
    return score


def search_products_by_query(products, query, limit=20):
    """Search products using token-based scoring. Returns sorted matches."""
    if not query or not query.strip():
        return products[:limit]

    scored = []
    for p in products:
        s = score_product(p, query)
        if s > 0:
            scored.append((s, p))

    scored.sort(key=lambda x: x[0], reverse=True)
    return [p for _, p in scored[:limit]]


def clean_search_query(message):
    """Remove filler words and punctuation from a user message to extract the search query.
    Keeps brand names, product names, and version numbers."""
    search_query = message
    # Strip trailing/leading punctuation that aren't part of product names
    search_query = re.sub(r'[?!.,;:]+', ' ', search_query)
    filler_words = [
        'find', 'me', 'show', 'search', 'for', 'get', 'do', 'you', 'have',
        'i', 'want', 'need', 'looking', 'can', 'please', 'could',
        'any', 'some', 'the', 'a', 'an', 'is', 'are', 'there',
        'what', 'which', 'where', 'how', 'about', 'like', 'would',
        'give', 'tell', 'list', 'all', 'of', 'with', 'and', 'or',
        'hi', 'hello', 'hey', 'thanks', 'thank', 'ok', 'okay',
    ]
    for word in filler_words:
        search_query = re.sub(rf'\b{word}\b', '', search_query, flags=re.IGNORECASE)
    return ' '.join(search_query.split()).strip()


# ── Routes ───────────────────────────────────────────────────────────────

@app.route('/ai/status')
def ai_status():
    """Diagnostic endpoint — shows whether the AI/LLM is configured and working."""
    status = {
        "anthropic_sdk_installed": Anthropic is not None,
        "kiro_api_key_set": bool(KIRO_API_KEY),
        "kiro_client_initialized": kiro_client is not None,
        "kiro_model": KIRO_MODEL,
        "kiro_base_url": KIRO_BASE_URL,
    }
    if kiro_client:
        # Quick test call
        try:
            test_resp = call_kiro("Say 'OK' in one word.", max_tokens=16)
            status["llm_test"] = "ok" if test_resp else "failed (empty response)"
            status["llm_test_response"] = test_resp
        except Exception as e:
            status["llm_test"] = f"error: {type(e).__name__}: {e}"
    else:
        status["llm_test"] = "skipped (client not initialized)"
        if not Anthropic:
            status["fix_hint"] = "Install anthropic SDK: pip install anthropic"
        elif not KIRO_API_KEY:
            status["fix_hint"] = "Set KIRO_API_KEY in your .env file"
    return jsonify(status)


@app.route('/')
def index():
    """API root — overview + quick link list."""
    manifest = load_manifest()
    base = get_base_url()
    ok = [m for m in manifest if m.get('status') == 'ok' and m.get('glb')]
    return jsonify({
        "service": "DSM-3D Model API",
        "total_models": len(ok),
        "endpoints": {
            "list_all":     f"{base}/models",
            "by_id":        f"{base}/models/<id>",
            "serve_glb":    f"{base}/models/<id>/<folder>/<file>",
            "viewer":       f"{base}/viewer/<id>",
        },
        "models": [
            {
                "id":   m["id"],
                "name": m["name"],
                "link": f"{base}/models/{m['id']}/{m['folder']}/{m['glb']}",
                "viewer": f"{base}/viewer/{m['id']}",
            }
            for m in ok
        ],
    })


@app.route('/models')
def list_models():
    """Return JSON array of all available models with live download links."""
    manifest = load_manifest()
    base = get_base_url()
    results = []
    for m in manifest:
        if m.get('status') != 'ok' or not m.get('glb'):
            continue
        results.append({
            "id":       m["id"],
            "name":     m["name"],
            "folder":   m["folder"],
            "filename": m["glb"],
            "link":     f"{base}/models/{m['id']}/{m['folder']}/{m['glb']}",
            "viewer":   f"{base}/viewer/{m['id']}",
            "status":   m["status"],
        })
    return jsonify({
        "count": len(results),
        "models": results,
    })


@app.route('/models/<pid>')
def get_model_by_id(pid):
    """Return info + live link for a single product by ID."""
    manifest = load_manifest()
    base = get_base_url()
    matches = [m for m in manifest if str(m.get('id')) == str(pid)]
    if not matches:
        abort(404, description=f"No model found for ID {pid}")
    m = matches[0]
    if m.get('status') != 'ok' or not m.get('glb'):
        abort(404, description=f"Model {pid} exists but has no GLB (status: {m.get('status')})")
    return jsonify({
        "id":       m["id"],
        "name":     m["name"],
        "folder":   m["folder"],
        "filename": m["glb"],
        "link":     f"{base}/models/{m['id']}/{m['folder']}/{m['glb']}",
        "viewer":   f"{base}/viewer/{m['id']}",
    })


@app.route('/models/<pid>/<folder>/<filename>')
def serve_glb(pid, folder, filename):
    """Serve the actual GLB file from models/{folder}/{filename}."""
    folder_path = os.path.join(MODELS_DIR, folder)
    file_path   = os.path.join(folder_path, filename)

    if not os.path.isfile(file_path):
        abort(404, description=f"File not found: {folder}/{filename}")

    response = send_from_directory(
        folder_path, filename,
        mimetype='model/gltf-binary',
    )
    # CORS so any frontend can fetch the model
    response.headers['Access-Control-Allow-Origin'] = '*'
    response.headers['Cache-Control'] = 'public, max-age=86400'
    return response


# ── New E-commerce Endpoints ───────────────────────────────────────────────

@app.route('/products/top')
def get_top_products():
    """Get top N products (curated/bestsellers)."""
    limit = int(request.args.get('limit', 10))
    manifest = load_manifest()
    base = get_base_url()
    
    # Get all valid products and enrich
    all_products = [enrich_product(m, base) for m in manifest 
                    if m.get('status') == 'ok' and m.get('glb')]
    
    # Simple "popularity" heuristic: prefer products with shorter names (more focused)
    # In real app, this would use actual sales/views data
    all_products.sort(key=lambda x: (len(x['name']), x['name']))
    
    return jsonify({
        "count": len(all_products[:limit]),
        "products": all_products[:limit],
    })


@app.route('/products')
def get_products():
    """Get products with filtering, sorting, pagination."""
    manifest = load_manifest()
    base = get_base_url()
    
    # Get all products and enrich
    all_products = [enrich_product(m, base) for m in manifest 
                    if m.get('status') == 'ok' and m.get('glb')]
    
    # Apply filters
    brand_filter = request.args.getlist('brand')
    category_filter = request.args.getlist('category')
    license_filter = request.args.getlist('licenseType')
    search_query = request.args.get('q', '').lower()
    
    filtered = all_products
    if brand_filter:
        filtered = [p for p in filtered if p['brand'] in brand_filter]
    if category_filter:
        # Hierarchical category mapping: parent → children
        # Only include brand-specific categories, NOT generic ones like "Agencies & Freelancers Software"
        CATEGORY_CHILDREN = {
            'Autodesk': ['Autodesk', 'Autodesk 2022', 'Autodesk 2023', 'Autodesk 2024', 'Autodesk 2025', 'Autodesk 2026',
                         'AutoCAD', '3ds Max', 'Civil 3D', 'Fusion 360', 'Inventor', 'Maya', 'Naviswork', 'Revit',
                         'AEC Collection 2025', 'DMC', 'MEC collection', 'Infodrainage'],
            'Microsoft Servers': ['Microsoft Servers', 'Exchange Server', 'Share Point Server',
                                  'Windows Server 2012', 'Windows Server 2016', 'Windows Server 2019',
                                  'Windows Server 2022', 'Windows Server 2025'],
            'Microsoft Office': ['Microsoft Office', 'Microsoft Office 2013', 'Microsoft Office 2016',
                                 'Microsoft Office 2019', 'Microsoft Office 2021', 'Microsoft Office 2024',
                                 'Microsoft Office 365', 'Microsoft Office For MAC', 'Office 2024'],
            'Office Applications': ['Office Applications', 'Microsoft Project', 'Microsoft Project 2024 Pro',
                                    'Microsoft Visio', 'Microsoft Visio 2024 Pro', 'Microsoft Visual Studio'],
            'SQL Server': ['SQL Server', 'SQL Server 2017', 'SQL Server 2019', 'SQL Server 2022', 'SQL Server 2025'],
            'Windows': ['Windows', 'Microsoft Windows 10', 'Microsoft Windows 11'],
            'Adobe': ['Adobe'],
            'SketchUp & V-Ray': ['SketchUp & V-Ray', 'SketchUp', 'V-Ray'],
        }
        # For brand-level category filters (e.g., "Autodesk"), use BRAND matching
        # instead of category expansion when the filter is a brand name
        BRAND_CATEGORIES = {'Autodesk', 'Adobe', 'Microsoft', 'SketchUp', 'Chaos', 'Kaspersky'}
        
        # Expand the category filter to include children
        expanded = set()
        brand_level_filters = set()
        for cf in category_filter:
            if cf in BRAND_CATEGORIES:
                brand_level_filters.add(cf)
            else:
                expanded.add(cf)
                if cf in CATEGORY_CHILDREN:
                    expanded.update(CATEGORY_CHILDREN[cf])
        
        if brand_level_filters and expanded:
            # Mix of brand-level and category-level filters
            filtered = [p for p in filtered if 
                        p.get('brand') in brand_level_filters or
                        any(c in expanded for c in p.get('categories', [p['category']]))]
        elif brand_level_filters:
            # Only brand-level filters
            filtered = [p for p in filtered if p.get('brand') in brand_level_filters]
        elif expanded:
            # Only category-level filters
            filtered = [p for p in filtered if any(c in expanded for c in p.get('categories', [p['category']]))]
    if license_filter:
        filtered = [p for p in filtered if p['licenseType'] in license_filter]
    if search_query:
        filtered = search_products_by_query(filtered, search_query, limit=len(filtered))
    
    # Apply sorting
    sort_by = request.args.get('sort', 'popular')
    if sort_by == 'price-low':
        filtered.sort(key=lambda x: float(re.sub(r'[^\d.]', '', x.get('price', '0'))))
    elif sort_by == 'price-high':
        filtered.sort(key=lambda x: float(re.sub(r'[^\d.]', '', x.get('price', '0'))), reverse=True)
    elif sort_by == 'name':
        filtered.sort(key=lambda x: x['name'])
    # 'popular' is default (already sorted by name length heuristic)
    
    # Pagination
    page = int(request.args.get('page', 1))
    limit = int(request.args.get('limit', 20))
    offset = (page - 1) * limit
    paginated = filtered[offset:offset + limit]
    
    return jsonify({
        "count": len(filtered),
        "page": page,
        "limit": limit,
        "totalPages": (len(filtered) + limit - 1) // limit,
        "products": paginated,
    })


@app.route('/products/<pid>')
def get_product_details(pid):
    """Get detailed product info by ID."""
    manifest = load_manifest()
    base = get_base_url()
    matches = [m for m in manifest if str(m.get('id')) == str(pid)]
    
    if not matches:
        abort(404, description=f"No product found for ID {pid}")
    
    m = matches[0]
    if m.get('status') != 'ok' or not m.get('glb'):
        abort(404, description=f"Product {pid} exists but has no GLB")
    
    product = enrich_product(m, base)
    
    # Add extra detail fields
    product['whatsIncluded'] = [
        "Genuine license key",
        "Email delivery within 24 hours",
        "Setup support included",
        "Official partner guarantee",
    ]
    product['platform'] = "Windows" if "Windows" in product['name'] else "Multi-platform"
    product['validity'] = "Lifetime" if product['licenseType'] == 'Lifetime' else "1 Year"
    
    return jsonify(product)


@app.route('/filters')
def get_filters():
    """Get available filter options from the actual product catalog."""
    manifest = load_manifest()
    base = get_base_url()
    all_products = [enrich_product(m, base) for m in manifest
                    if m.get('status') == 'ok' and m.get('glb')]

    from collections import Counter
    brand_counts = Counter(p['brand'] for p in all_products)
    category_counts = Counter()
    for p in all_products:
        for c in p.get('categories', [p['category']]):
            category_counts[c] += 1
    license_counts = Counter(p['licenseType'] for p in all_products)

    return jsonify({
        "brands": [{"name": b, "count": c} for b, c in brand_counts.most_common()],
        "categories": [{"name": cat, "count": c} for cat, c in category_counts.most_common()],
        "licenseTypes": [{"name": lt, "count": c} for lt, c in license_counts.most_common()],
    })


@app.route('/search')
def search_products():
    """Normal text search across products."""
    query = request.args.get('q', '').strip()
    if not query:
        return jsonify({"count": 0, "products": [], "suggestions": []})
    
    manifest = load_manifest()
    base = get_base_url()
    all_products = [enrich_product(m, base) for m in manifest 
                    if m.get('status') == 'ok' and m.get('glb')]
    
    results = search_products_by_query(all_products, query, limit=20)
    
    # Generate suggestions based on token matching
    query_lower = query.lower()
    query_tokens = [t for t in query_lower.split() if len(t) > 1]
    suggestions = []
    brands = set(p['brand'] for p in all_products 
                 if any(t in p['brand'].lower() for t in query_tokens))
    categories = set(p['category'] for p in all_products 
                     if any(t in p['category'].lower() for t in query_tokens))
    suggestions.extend(list(brands)[:3])
    suggestions.extend(list(categories)[:3])
    
    return jsonify({
        "count": len(results),
        "products": results,
        "suggestions": suggestions[:5],
    })


@app.route('/ai-search')
def ai_search():
    """AI-powered search with intent interpretation."""
    query = request.args.get('q', '').strip()
    if not query:
        return jsonify({
            "intent": "browse",
            "filters": {},
            "productIds": [],
            "suggestions": [],
        })
    
    manifest = load_manifest()
    base = get_base_url()
    all_products = [enrich_product(m, base) for m in manifest 
                    if m.get('status') == 'ok' and m.get('glb')]
    
    # Get available brands and categories for context
    brands = sorted(set(p['brand'] for p in all_products))
    categories = sorted(set(p['category'] for p in all_products))
    
    # Use Kiro for intelligent search interpretation
    if kiro_client:
        system_prompt = f"""You are an AI assistant helping users search a software license store. 
Available brands: {', '.join(brands)}
Available categories: {', '.join(categories)}

Analyze the user's search query and determine:
1. Intent (browse, search, budget_search, etc.)
2. Relevant filters (brand, category, licenseType)
3. Top product IDs that match (return as comma-separated list)

Respond in JSON format:
{{
  "intent": "search",
  "filters": {{"brand": ["Microsoft"], "category": ["Office"]}},
  "productIds": ["123", "456"],
  "suggestions": ["Microsoft Office", "Windows 11"]
}}"""
        
        prompt = f"""User search query: "{query}"

Analyze this query and return JSON with intent, filters, productIds, and suggestions."""
        
        ai_response = call_kiro(prompt, system_prompt, max_tokens=2048)
        
        if ai_response:
            # Try to parse JSON from response
            try:
                json_match = re.search(r'\{[^{}]*(?:\{[^{}]*\}[^{}]*)*\}', ai_response, re.DOTALL)
                if json_match:
                    parsed = json.loads(json_match.group(0))
                    # Validate and return
                    return jsonify({
                        "intent": parsed.get("intent", "search"),
                        "filters": parsed.get("filters", {}),
                        "productIds": parsed.get("productIds", [])[:10],
                        "suggestions": parsed.get("suggestions", [])[:5],
                    })
            except:
                pass
    
    # Fallback — use token search + brand detection
    query_lower = query.lower()
    intent = "search"
    filters = {}
    
    # Brand detection using comprehensive keyword lists
    brand_keywords = {
        'Microsoft': ['microsoft', 'windows', 'office', 'sql', 'visio', 'project', 'dynamics', 'power bi', 'visual studio', 'exchange', 'sharepoint'],
        'Autodesk': ['autodesk', 'autocad', 'revit', 'maya', '3ds max', 'civil 3d', 'naviswork', 'inventor', 'fusion 360'],
        'Adobe': ['adobe', 'photoshop', 'illustrator', 'premiere', 'creative cloud', 'acrobat'],
        'Chaos': ['chaos', 'v-ray', 'enscape', 'corona'],
        'SketchUp': ['sketchup', 'sketch up'],
        'Kaspersky': ['kaspersky'],
    }
    for brand_name, keywords in brand_keywords.items():
        if any(kw in query_lower for kw in keywords):
            filters['brand'] = [brand_name]
            break
    
    # Category detection
    category_keywords = {
        'Microsoft Office': ['office', 'word', 'excel', 'powerpoint', 'outlook'],
        'Microsoft Windows 11': ['windows 11'],
        'Microsoft Windows 10': ['windows 10'],
        'AutoCAD': ['autocad', 'cad'],
        'Revit': ['revit', 'bim'],
        'Maya': ['maya', 'animation'],
        'SQL Server': ['sql server', 'sql'],
        'Microsoft Servers': ['server 2022', 'server 2025', 'server 2019'],
    }
    for cat_name, keywords in category_keywords.items():
        if any(kw in query_lower for kw in keywords):
            filters['category'] = [cat_name]
            break
    
    if 'cheap' in query_lower or 'budget' in query_lower or 'affordable' in query_lower:
        intent = "budget_search"
    
    # Use token-based search on all products
    text_matches = search_products_by_query(all_products, query, limit=10)
    
    product_ids = [str(p['id']) for p in text_matches[:10]]
    suggestions = []
    if text_matches:
        top_brands = list(set(p['brand'] for p in text_matches[:5]))
        top_cats = list(set(p['category'] for p in text_matches[:5]))
        suggestions.extend(top_brands[:2])
        suggestions.extend(top_cats[:2])
    
    return jsonify({
        "intent": intent,
        "filters": filters,
        "productIds": product_ids,
        "suggestions": suggestions[:5],
    })


@app.route('/ai/chat', methods=['POST'])
def ai_chat():
    """Global AI chat endpoint — always uses LLM when available."""
    data = request.get_json() or {}
    message = data.get('message', '').strip()
    context = data.get('context', {})
    
    if not message:
        return jsonify({"error": "Message required"}), 400
    
    # Get product catalog context
    manifest = load_manifest()
    base = get_base_url()
    all_products = [enrich_product(m, base) for m in manifest 
                    if m.get('status') == 'ok' and m.get('glb')]
    brands = sorted(set(p['brand'] for p in all_products))
    categories = sorted(set(p['category'] for p in all_products))
    
    # ── Step 1: Detect intent BEFORE searching ──
    msg_lower = message.lower().strip()
    search_query = clean_search_query(message)
    
    # Classify intent
    greeting_words = ['hello', 'hi', 'hey', 'greetings', 'good morning', 'good afternoon',
                      'good evening', 'howdy', 'sup', 'yo', 'salam', 'hola', 'whats up',
                      "what's up", 'how are you']
    help_words = ['help', 'what can you do', 'what do you do', 'how does this work',
                  'what is this', 'who are you', 'capabilities', 'features']
    thanks_words = ['thank', 'thanks', 'thx', 'appreciate', 'cheers', 'great job',
                    'awesome', 'cool', 'nice', 'perfect', 'brilliant']
    store_words = ['browse', 'store', 'catalog', 'catalogue', 'all products', 'show me everything',
                   'what do you sell', 'what products', 'what software']
    compare_words = ['compare', 'vs', 'versus', 'difference between', 'which is better',
                     'which one', 'comparison']
    price_words = ['price', 'cost', 'how much', 'pricing', 'budget', 'cheapest', 'affordable',
                   'expensive', 'discount', 'deal']
    
    is_greeting = any(w in msg_lower for w in greeting_words) and len(msg_lower.split()) <= 5
    is_help = any(w in msg_lower for w in help_words)
    is_thanks = any(w in msg_lower for w in thanks_words) and len(msg_lower.split()) <= 6
    is_store_browse = any(w in msg_lower for w in store_words)
    is_compare = any(w in msg_lower for w in compare_words)
    is_price_query = any(w in msg_lower for w in price_words)
    
    # Detect brand from message
    brand_filter = None
    brand_keywords = {
        'Autodesk': ['autodesk', 'autocad', 'revit', 'maya', '3ds max', 'civil 3d', 'naviswork', 'inventor', 'fusion 360'],
        'Microsoft': ['microsoft', 'windows', 'office', 'sql server', 'visio', 'project', 'dynamics', 'power bi', 'visual studio', 'exchange', 'sharepoint'],
        'Adobe': ['adobe', 'photoshop', 'illustrator', 'premiere', 'creative cloud', 'acrobat'],
        'Chaos': ['chaos', 'v-ray', 'enscape', 'corona'],
        'SketchUp': ['sketchup', 'sketch up'],
        'Kaspersky': ['kaspersky'],
    }
    for brand_name, keywords in brand_keywords.items():
        if any(kw in msg_lower for kw in keywords):
            brand_filter = [brand_name]
            break
    
    # Determine if this is a product search (has brand/product keywords or meaningful search terms)
    has_product_intent = bool(brand_filter) or bool(search_query and len(search_query) >= 2)
    # Don't treat pure conversational messages as product searches
    if is_greeting or is_help or is_thanks:
        has_product_intent = False
    
    # Search products only if there's a product intent
    found_products = []
    if has_product_intent:
        matching_products = all_products
        if brand_filter:
            matching_products = [p for p in matching_products if p['brand'] in brand_filter]
        
        query_is_brand_name = brand_filter and search_query and search_query.lower().strip() in [b.lower() for b in brand_filter]
        if search_query and not query_is_brand_name:
            refined = search_products_by_query(matching_products, search_query, limit=10)
            if refined:
                matching_products = refined
        found_products = matching_products[:6]
    
    # Build product context for the LLM
    product_context = ""
    if found_products:
        product_lines = []
        for p in found_products:
            desc_snippet = (p.get('description', '') or '')[:150]
            product_lines.append(f"- ID:{p['id']} | {p['name']} | {p['price']} | {p.get('category','')} | {p.get('licenseType','')} | {desc_snippet}")
        product_context = f"\n\nMATCHING PRODUCTS FOUND ({len(found_products)}):\n" + "\n".join(product_lines)
    
    # ── Step 2: Call LLM with full context ──
    if kiro_client:
        system_prompt = f"""You are the DSM Online concierge — a friendly, sharp, human-sounding assistant for a premium software license store in the UAE.

RULES:
1. Keep answers SHORT — 1-3 sentences max for simple questions. No essays.
2. Sound like a helpful human, not a robot. Use casual but professional tone.
3. When products are found, just say something like "Here's what I found:" or "Got it! Check these out:" — the UI shows product cards automatically, so don't list them all out.
4. Use **bold** for key info (prices, product names, user counts). Use bullet points only when listing 3+ things.
5. For comparisons, use a compact markdown table.
6. Extract user/seat/core counts from product names (e.g., "5 Users" → 5 users, "16 Core" → 16 cores, Professional/Standard = 1 user).
7. If you're unsure or can't answer fully, say: "💬 [Chat with our team on WhatsApp](https://wa.me/97125844433) for more details!"
8. Never make up specs. If it's not in the data, don't guess.
9. For greetings, respond warmly and briefly. Ask how you can help.
10. For "compare" without specifying products, ask which products they want to compare.

STORE: Brands: {', '.join(brands)} | Currency: AED | Delivery: Digital email within 24hrs | All licenses genuine.

ACTIONS (append as JSON after "ACTIONS:" on new line when needed):
- {{"type": "NAVIGATE", "payload": {{"path": "/store"}}}}
- {{"type": "APPLY_FILTERS", "payload": {{"brand": ["Microsoft"]}}}}
- {{"type": "SET_SEARCH", "payload": {{"query": "autocad 2026"}}}}
- {{"type": "OPEN_PRODUCT", "payload": {{"productId": "123"}}}}
{product_context}"""
        
        prompt = f""""{message}"

Reply in 1-3 sentences. Be direct. If products were found above, briefly mention them. Add ACTIONS: if the user wants to search/filter/navigate."""
        
        ai_response = call_kiro(prompt, system_prompt, max_tokens=1536)
        
        if ai_response:
            # Extract actions
            actions = []
            actions_match = re.search(r'ACTIONS:\s*(\[.*?\])', ai_response, re.DOTALL | re.IGNORECASE)
            if actions_match:
                try:
                    actions = json.loads(actions_match.group(1))
                    if not isinstance(actions, list):
                        actions = [actions]
                except:
                    pass
            
            # Clean message text (remove actions section)
            message_text = re.sub(r'ACTIONS:.*$', '', ai_response, flags=re.DOTALL | re.IGNORECASE).strip()
            
            # Generate contextual suggestions
            suggestions = []
            if found_products:
                suggestions.append("Tell me more about these")
                suggestions.append("Compare options")
            if brand_filter:
                suggestions.append(f"More {brand_filter[0]} products")
            if not suggestions:
                suggestions = ["Browse Store", "Microsoft Products", "Autodesk Products"]
            
            return jsonify({
                "message": message_text,
                "actions": actions,
                "suggestions": suggestions[:5],
                "products": found_products,
            })
        else:
            print(f"[AI Chat] LLM call returned None for message: {message[:80]}")
    
    # ── No LLM available — return an error, not a fake response ──
    reason = "AI service is temporarily unavailable."
    if not kiro_client:
        if not Anthropic:
            reason = "AI service not configured: anthropic SDK is not installed on the server."
        elif not KIRO_API_KEY:
            reason = "AI service not configured: KIRO_API_KEY is not set in the server environment."
        else:
            reason = "AI service not configured: failed to initialize the AI client."
    else:
        reason = "AI service error: the LLM call failed. Please try again."
    
    print(f"[AI Chat] Returning error — kiro_client={'yes' if kiro_client else 'no'}, "
          f"Anthropic={'yes' if Anthropic else 'no'}, "
          f"KIRO_API_KEY={'set' if KIRO_API_KEY else 'NOT SET'}")
    
    return jsonify({
        "error": reason,
        "message": f"⚠️ {reason}\n\n💬 [Chat with our team on WhatsApp](https://wa.me/97125844433) for immediate assistance!",
        "actions": [],
        "suggestions": [],
        "products": [],
    }), 503


@app.route('/ai/product-chat', methods=['POST'])
def product_chat():
    """Product-scoped AI chat — always uses LLM when available."""
    data = request.get_json() or {}
    message = data.get('message', '').strip()
    product_id = data.get('productId')
    
    if not message:
        return jsonify({"error": "Message required"}), 400
    
    if not product_id:
        return jsonify({"error": "productId required"}), 400
    
    # Get product info
    manifest = load_manifest()
    matches = [m for m in manifest if str(m.get('id')) == str(product_id)]
    if not matches:
        return jsonify({"error": "Product not found"}), 404
    
    product = enrich_product(matches[0], get_base_url())
    desc = product.get('description', '') or ''
    full_desc = product.get('fullDescription', '') or ''
    
    # Also find similar products for comparison context
    base = get_base_url()
    all_products = [enrich_product(m, base) for m in manifest 
                    if m.get('status') == 'ok' and m.get('glb')]
    # Same-brand products
    same_brand = [p for p in all_products 
               if p['brand'] == product['brand'] and str(p['id']) != str(product_id)][:5]
    # Cross-brand: detect if the user message mentions other brands
    msg_lower_pre = message.lower()
    cross_brand_products = []
    cross_brand_keywords = {
        'Autodesk': ['autodesk', 'autocad', 'revit', 'maya', '3ds max', 'civil 3d', 'naviswork', 'inventor', 'mudbox', 'flame'],
        'Microsoft': ['microsoft', 'windows', 'office', 'sql server', 'visio', 'project', 'dynamics', 'power bi', 'visual studio'],
        'Adobe': ['adobe', 'photoshop', 'illustrator', 'premiere', 'creative cloud', 'acrobat'],
        'Chaos': ['chaos', 'v-ray', 'corona'],
        'SketchUp': ['sketchup'],
    }
    for brand_name, keywords in cross_brand_keywords.items():
        if brand_name != product['brand'] and any(kw in msg_lower_pre for kw in keywords):
            cross_brand_products = [p for p in all_products 
                                    if p['brand'] == brand_name and str(p['id']) != str(product_id)][:5]
            break
    
    similar = same_brand
    similar_context = ""
    if same_brand:
        lines = [f"- {p['name']} | {p['price']} | {p.get('category','')}" for p in same_brand]
        similar_context = f"\n\nSAME-BRAND PRODUCTS ({product['brand']}):\n" + "\n".join(lines)
    if cross_brand_products:
        lines2 = [f"- {p['name']} | {p['price']} | {p.get('category','')}" for p in cross_brand_products]
        similar_context += f"\n\nCROSS-BRAND PRODUCTS (requested by user):\n" + "\n".join(lines2)
        similar = same_brand + cross_brand_products
    
    # ── Extract licensing details from product name ──
    name_lower = product['name'].lower()
    user_match = re.search(r'(\d+)\s*[-–]?\s*(?:user|users|seat|seats)', name_lower)
    core_match = re.search(r'(\d+)\s*[-–]?\s*(?:core|cores)', name_lower)
    device_match = re.search(r'(\d+)\s*[-–]?\s*(?:device|devices|pc|pcs)', name_lower)
    cal_match = re.search(r'(\d+)\s*[-–]?\s*(?:cal|cals)', name_lower)
    year_match = re.search(r'(\d+)\s*[-–]?\s*(?:year|years|yr|yrs)', name_lower)
    
    licensing_details = []
    if user_match:
        licensing_details.append(f"**{user_match.group(1)} user(s)/seats** included")
    elif '1 user' not in name_lower and 'single' not in name_lower:
        # Standard license — 1 user unless stated otherwise
        if 'professional' in name_lower or 'standard' in name_lower or 'home' in name_lower:
            licensing_details.append("**1 user/PC** — single-user license")
    if core_match:
        licensing_details.append(f"**{core_match.group(1)} core(s)** server license")
    if device_match:
        licensing_details.append(f"**{device_match.group(1)} device(s)/PC(s)** covered")
    if cal_match:
        licensing_details.append(f"**{cal_match.group(1)} CAL(s)** (Client Access Licenses)")
    if year_match:
        licensing_details.append(f"**{year_match.group(1)} year(s)** subscription")
    elif product['licenseType'] == 'Lifetime':
        licensing_details.append("**Lifetime** — one-time purchase, no recurring fees")
    elif product['licenseType'] == 'Subscription':
        licensing_details.append("**Subscription** — typically annual renewal")
    
    licensing_text = "\n".join(f"- {d}" for d in licensing_details) if licensing_details else "- Not specified in the product listing"

    # Build similar products table for comparisons (includes cross-brand)
    all_comparable = similar  # already includes cross-brand if detected
    similar_table = ""
    if all_comparable:
        sim_rows = []
        for s in all_comparable:
            s_user = re.search(r'(\d+)\s*[-–]?\s*(?:user|seat)', s['name'].lower())
            s_core = re.search(r'(\d+)\s*[-–]?\s*(?:core)', s['name'].lower())
            user_info = f"{s_user.group(1)} user(s)" if s_user else ("1 user" if 'standard' in s['name'].lower() or 'professional' in s['name'].lower() else "—")
            core_info = f"{s_core.group(1)} core(s)" if s_core else "—"
            sim_rows.append(f"| {s['name'][:60]} | {s['brand']} | {s['price']} | {s.get('licenseType', '—')} | {user_info} | {s.get('category','')} |")
        similar_table = "\n\nAVAILABLE PRODUCTS FOR COMPARISON:\n\n| Product | Brand | Price | License | Users | Category |\n|---------|-------|-------|---------|-------|----------|\n" + "\n".join(sim_rows)

    # ── Call LLM ──
    if kiro_client:
        system_prompt = f"""You are an expert product specialist for DSM Online, a premium software license store based in the UAE.
You are answering questions about a specific product. Use ONLY the data below — never invent specs.

## Current Product
- **Name:** {product['name']}
- **Brand:** {product['brand']}
- **Price:** {product['price']}
- **License Type:** {product['licenseType']}
- **Categories:** {', '.join(product.get('categories', [product['category']]))}
- **SKU:** {product.get('sku', 'N/A')}
- **Stock:** {product.get('stockStatus', 'In Stock')}

## Licensing Details
{licensing_text}

## Description
{desc[:500] if desc else 'No description available.'}

## Full Details
{full_desc[:1200] if full_desc else 'No additional details.'}
{similar_table or similar_context}

## Response Style
- Use proper markdown: **bold** text, ### headings, bullet points, numbered lists
- Structure your answers with clear sections when appropriate
- For **comparisons**: ALWAYS use a **markdown table** comparing Price, License Type, Users/Seats, Category, Best For
- For **user/seat/core questions**: extract counts from product names. "Professional Plus" = 1 user/PC. "5 User" = 5 users. "16 Core" = 16 cores. NEVER say "contact support" if the count is inferable.
- For **"what's included"**: use bullet points listing features
- For **"who is this for"**: describe the target audience in 2-3 sentences with examples
- Sound helpful and knowledgeable — not robotic
- If the user mentions a specific brand for comparison, use the CROSS-BRAND PRODUCTS list provided above
- Delivery is digital via email within 24 hours. All licenses are genuine.
- If data is insufficient: "💬 [Chat with us on WhatsApp](https://wa.me/97125844433) for more details!" """
        
        prompt = f"""User question about {product['name']}: "{message}"

Give a thorough, well-structured answer using the product data. Use markdown formatting (headings, bold, tables, bullet points)."""
        
        ai_response = call_kiro(prompt, system_prompt, max_tokens=2048)
        
        if ai_response:
            # Contextual suggestions based on the question
            msg_lower = message.lower()
            suggestions = []
            if 'price' in msg_lower or 'cost' in msg_lower:
                suggestions = ["Compare with alternatives", "What's included?", "Volume licensing?"]
            elif 'user' in msg_lower or 'seat' in msg_lower:
                suggestions = ["Volume licensing?", "What's included?", "Setup steps"]
            elif 'setup' in msg_lower or 'install' in msg_lower:
                suggestions = ["System requirements?", "What's included?", "Contact support"]
            elif 'compare' in msg_lower:
                suggestions = ["Tell me more", "Pricing details", "Who is this for?"]
            else:
                suggestions = ["What's included?", "Compare options", "Setup steps", "How many users?"]
            
            return jsonify({
                "message": ai_response,
                "actions": [],
                "suggestions": suggestions[:5],
            })
    
    # ── No LLM available — return an error, not a fake response ──
    reason = "AI service is temporarily unavailable."
    if not kiro_client:
        if not Anthropic:
            reason = "AI service not configured: anthropic SDK is not installed on the server."
        elif not KIRO_API_KEY:
            reason = "AI service not configured: KIRO_API_KEY is not set in the server environment."
        else:
            reason = "AI service not configured: failed to initialize the AI client."
    else:
        reason = "AI service error: the LLM call failed. Please try again."
    
    print(f"[Product Chat] Returning error — kiro_client={'yes' if kiro_client else 'no'}, "
          f"Anthropic={'yes' if Anthropic else 'no'}, "
          f"KIRO_API_KEY={'set' if KIRO_API_KEY else 'NOT SET'}")
    
    return jsonify({
        "error": reason,
        "message": f"⚠️ {reason}\n\n💬 [Chat with our team on WhatsApp](https://wa.me/97125844433) for immediate assistance!",
        "actions": [],
        "suggestions": [],
    }), 503


@app.route('/viewer/<pid>')
def viewer(pid):
    """Inline 3D viewer for a product by ID."""
    manifest = load_manifest()
    base = get_base_url()
    matches = [m for m in manifest if str(m.get('id')) == str(pid)]
    if not matches or matches[0].get('status') != 'ok':
        abort(404, description=f"No model for ID {pid}")
    m = matches[0]
    glb_url = f"{base}/models/{m['id']}/{m['folder']}/{m['glb']}"

    html = VIEWER_TEMPLATE.replace("{{GLB_URL}}", glb_url)\
                           .replace("{{PRODUCT_NAME}}", m.get("name", "Product"))\
                           .replace("{{PRODUCT_ID}}", str(m.get("id", "")))
    return html


# ── Inline viewer template ───────────────────────────────────────────────

VIEWER_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{{PRODUCT_NAME}} — 3D Viewer</title>
<style>
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;
     background:#0f0f1a;color:#fff;overflow:hidden;height:100vh}
#info{position:fixed;top:16px;left:16px;z-index:10;
      background:rgba(0,0,0,.55);backdrop-filter:blur(12px);
      padding:12px 20px;border-radius:10px;border:1px solid rgba(255,255,255,.08)}
#info h2{font-size:14px;opacity:.6;letter-spacing:1px;text-transform:uppercase}
#info h1{font-size:20px;margin-top:2px}
#info .id{font-size:11px;opacity:.4;margin-top:4px}
#c{width:100vw;height:100vh}
.loading{position:fixed;top:50%;left:50%;transform:translate(-50%,-50%);
         text-align:center;color:#888}
.spinner{width:32px;height:32px;border:3px solid rgba(255,255,255,.08);
         border-top-color:#667eea;border-radius:50%;
         animation:s .7s linear infinite;margin:0 auto 10px}
@keyframes s{to{transform:rotate(360deg)}}
</style>
</head>
<body>
<div id="info">
  <h2>DSM 3D</h2>
  <h1>{{PRODUCT_NAME}}</h1>
  <div class="id">ID {{PRODUCT_ID}}</div>
</div>
<div class="loading" id="loader"><div class="spinner"></div><span>Loading…</span></div>
<canvas id="c"></canvas>

<script type="importmap">
{"imports":{"three":"https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.module.js",
"three/addons/":"https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/"}}
</script>
<script type="module">
import*as THREE from'three';
import{GLTFLoader}from'three/addons/loaders/GLTFLoader.js';
import{OrbitControls}from'three/addons/controls/OrbitControls.js';

const canvas=document.getElementById('c');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true});
renderer.setPixelRatio(Math.min(devicePixelRatio,2));
renderer.setSize(innerWidth,innerHeight);
renderer.toneMapping=THREE.ACESFilmicToneMapping;
renderer.toneMappingExposure=1.2;
renderer.outputColorSpace=THREE.SRGBColorSpace;

const scene=new THREE.Scene();
scene.background=new THREE.Color(0x0f0f1a);

const camera=new THREE.PerspectiveCamera(45,innerWidth/innerHeight,.1,100);
camera.position.set(2.5,1.5,2.5);

scene.add(new THREE.AmbientLight(0xffffff,.5));
const key=new THREE.DirectionalLight(0xffffff,1);key.position.set(4,6,4);scene.add(key);
const fill=new THREE.DirectionalLight(0xb0c4ff,.4);fill.position.set(-4,3,-2);scene.add(fill);
const rim=new THREE.DirectionalLight(0xffd4a8,.3);rim.position.set(0,2,-5);scene.add(rim);

const ctrl=new OrbitControls(camera,canvas);
ctrl.enableDamping=true;ctrl.dampingFactor=.08;
ctrl.autoRotate=true;ctrl.autoRotateSpeed=1.5;

new GLTFLoader().load("{{GLB_URL}}",(gltf)=>{
  const m=gltf.scene;
  m.traverse(c=>{if(c.isMesh){
    const mats=Array.isArray(c.material)?c.material:[c.material];
    mats.forEach(mt=>{if(mt.map){
      mt.map.wrapS=THREE.ClampToEdgeWrapping;
      mt.map.wrapT=THREE.ClampToEdgeWrapping;
      mt.map.minFilter=THREE.LinearMipmapLinearFilter;
      mt.map.anisotropy=renderer.capabilities.getMaxAnisotropy();
      mt.map.colorSpace=THREE.SRGBColorSpace;
      mt.map.needsUpdate=true}; mt.needsUpdate=true})}});
  const box=new THREE.Box3().setFromObject(m);
  const cen=box.getCenter(new THREE.Vector3());
  const sz=box.getSize(new THREE.Vector3());
  const sc=2/Math.max(sz.x,sz.y,sz.z);
  m.scale.multiplyScalar(sc);m.position.sub(cen.multiplyScalar(sc));
  scene.add(m);
  document.getElementById('loader').style.display='none';
},undefined,e=>{
  document.getElementById('loader').innerHTML='<span style="color:#ef4444">Error loading model</span>';
  console.error(e);
});

addEventListener('resize',()=>{
  camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();
  renderer.setSize(innerWidth,innerHeight)});

(function animate(){requestAnimationFrame(animate);ctrl.update();renderer.render(scene,camera)})();
</script>
</body>
</html>"""


# ── CORS preflight ───────────────────────────────────────────────────────

@app.after_request
def add_cors(resp):
    resp.headers['Access-Control-Allow-Origin'] = '*'
    resp.headers['Access-Control-Allow-Headers'] = 'Content-Type'
    resp.headers['Access-Control-Allow-Methods'] = 'GET, POST, OPTIONS'
    return resp


@app.route('/ai/chat', methods=['OPTIONS'])
@app.route('/ai/product-chat', methods=['OPTIONS'])
def handle_options():
    """Handle CORS preflight."""
    return '', 200


# ── Main ─────────────────────────────────────────────────────────────────

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='DSM-3D Model API')
    parser.add_argument('--port', type=int, default=5051, help='Port (default 5051)')
    parser.add_argument('--host', default='0.0.0.0', help='Host (default 0.0.0.0)')
    args = parser.parse_args()

    if not os.path.isdir(MODELS_DIR):
        print(f"WARNING: {MODELS_DIR}/ does not exist yet. Run batch_process.py first.")
        os.makedirs(MODELS_DIR, exist_ok=True)

    print(f"\n🚀 DSM-3D API starting on http://{args.host}:{args.port}")
    print(f"   Models dir:  {MODELS_DIR}")

    manifest = load_manifest()
    ok = [m for m in manifest if m.get('status') == 'ok' and m.get('glb')]
    print(f"   Models ready: {len(ok)}")
    print(f"\n   Endpoints:")
    print(f"     GET /              → API info + all products")
    print(f"     GET /models        → JSON list with live GLB links")
    print(f"     GET /models/<id>   → single product by ID")
    print(f"     GET /viewer/<id>   → 3D viewer in browser")
    print()

    app.run(host=args.host, port=args.port, debug=True)

